### ISSUE TITLE
TypeError: yaml.load is not a function

### ISSUE THREAD

**Issue by happyskey** [Wenmoux/checkbox#107]
## 开始执行... 2021-11-04 10:27:34

当前是青龙面板,路径：/ql
/ql/scripts/Wenmoux_checkbox_index.js:22
    } else config = yaml.load(fs.readFileSync(`/${QL}/config/config.yml`, 'utf8'));
                         ^

TypeError: yaml.load is not a function
    at Object.<anonymous> (/ql/scripts/Wenmoux_checkbox_index.js:22:26)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

## 执行结束... 2021-11-04 10:27:34 耗时 0 秒

请教一下：依赖，在线校验证都弄了，这个报错怎么解决，谢谢

**Comment by Wenmoux** [comment]
@happyskey 重装下依赖..

**Comment by uniqueww** [comment]
同样问题，请问楼主如何解决的

**Comment by happyskey** [comment]
pnpm install axios crypto crypto-js fs iconv-lite js-yaml yargs




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月4日(星期四) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Wenmoux/checkbox] TypeError: yaml.load is not a function (Issue #107)





 
同样问题，请问楼主如何解决的
 
&mdash;
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Wenmoux** [comment]
就是依赖问题

重装就行

**Comment by Oreomeow** [comment]
全局安装的尝试本地安装

**Comment by uniqueww** [comment]
> pnpm install axios crypto crypto-js fs iconv-lite js-yaml yargs

在docker容器中执行此命令，依旧报错

[root@VM-0-13-centos ~]# pnpm install axios crypto crypto-js fs iconv-lite js-yaml yargs
-bash: pnpm: command not found

**Comment by uniqueww** [comment]
已解决，谢谢各位
