### ISSUE TITLE
BUG反馈：直接运行会报错

### ISSUE THREAD

**Issue by BillScott1024** [Wenmoux/checkbox#11]
反馈几个BUG
1. sfacg.js 脚本里面，没有exports module，会直接运行task()，不知道是不是作者的测试代码忘了改
![image](https://user-images.githubusercontent.com/22955480/106386241-07053180-640f-11eb-9856-cbf920c71dd1.png)
2. sfacg.js 里的info方法会报错 **查询失败**，显示需要登录了才能获取信息，但是我已经填过cookies了。
3. sfacg.js 里的console.log(result)会报错 result找不到，不知道是不是测试代码没删。把这句注释就好了
![image](https://user-images.githubusercontent.com/22955480/106386391-ba6e2600-640f-11eb-8e3d-8913fab309ff.png)

**Comment by Wenmoux** [comment]
啊 1和3确实是忘了改回去(*´﹃｀*)2不太清楚 我自己没问题 ←_←感谢反馈

**Comment by BillScott1024** [comment]
> 啊 1和3确实是忘了改回去(_´﹃｀_)2不太清楚 我自己没问题 ←_←感谢反馈

2 我这边改了UA就正常了
