### ISSUE TITLE
联想智选签到

### ISSUE THREAD

**Issue by lxsb11122** [Wenmoux/checkbox#116]
联想签到那个baseinfo怎么获取啊，找半天找不到

**Comment by Wenmoux** [comment]
@lxsb11122 找不到不找不就好了 又不是必须填

**Comment by Wenmoux** [comment]
都说了在请求头里 个人中心随便点几下就不可能没有

**Comment by lxsb11122** [comment]
> @lxsb11122

一直登录失败，账号密码没问题
