### ISSUE TITLE
请求增加动漫字幕论坛VCB-Studio的自动签到

### ISSUE THREAD

**Issue by lilyblessing** [Wenmoux/checkbox#117]
站点: [ACGRIP](https://bbs.acgrip.com/) 是基于discuz做的论坛 

[签到页面](https://bbs.acgrip.com/dsu_paulsign-sign.html)

点一下申请就能完成的   [每日任务页面](https://bbs.acgrip.com/home.php?mod=task)

**Comment by Wenmoux** [comment]
已✓
