### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by 17huiwei** [Wenmoux/checkbox#119]
一亩三分地、猫耳FM提示“不存在该脚本文件,请确认输入是否有误”，看了一下，的确scripts目录里面没有这两个
龙空论坛提示"签到接口请求出错"
奥拉星找不到抓包内容

**Comment by Wenmoux** [comment]
@17huiwei ym三分地已经删了  
猫耳 自己看脚本名字..    
说了任务名看脚本名而不是配置名   
奥拉星..就抓个cookie咋可能抓不到
