### ISSUE TITLE
吾爱破解签到失效

### ISSUE THREAD

**Issue by andywang425** [Wenmoux/checkbox#12]
我自己抓包看了看，在吾爱签到时会发出两个GET请求：  
一个是脚本中已经有的
`https://www.52pojie.cn/home.php?mod=task&do=apply&id=2 `  
第二个是  
`https://www.52pojie.cn/home.php?mod=task&do=draw&id=2 `
  
感觉吾爱似乎把签到看作是一种任务，第一个API申请任务，第二个API完成任务。  
希望大佬能修复一下。

**Comment by Wenmoux** [comment]
我看了下
在我这是没问题的
![](https://cdn.jsdelivr.net/gh/Wenmoux/wenpic/other/309255730659995.jpg)
