### ISSUE TITLE
龙空失效了；爱企查还是有几个任务完成不了，以及收不到消息推送了

### ISSUE THREAD

**Issue by fuduxixi** [Wenmoux/checkbox#126]
龙空失效了；爱企查还是有几个任务完成不了，以及收不到消息推送了，其他的倒是推送正常

**Comment by fuduxixi** [comment]
@https://github.com/Wenmoux/checkbox/issues/114

**Comment by Wenmoux** [comment]
推送我没问题....
任务那个有的我没写比如评论
还有个看运气
还有个需要自己抓exportkey

**Comment by yunv7** [comment]
> 推送我没问题.... 任务那个有的我没写比如评论 还有个看运气 还有个需要自己抓exportkey
> 
> 龙空那个依稀记得链接我都打不开了 忘了

龙空现在lkong.cn弃用了 地址统一用www.lkong.com了 而且也改版了 不是原来的样子了
