### ISSUE TITLE
爱企查日常任务 CX12011: "点赞观点" 出错

### ISSUE THREAD

**Issue by lxr760** [Wenmoux/checkbox#127]
日志如下
开始任务：点赞观点
(node:20009) UnhandledPromiseRejectionWarning: ReferenceError: nid is not defined
at dotask (/ql/scripts/raw_Scripts_ql_aiqicha.js:188:9)
at async aqc (/ql/scripts/raw_Scripts_ql_aiqicha.js:223:9)
(Use node --trace-warnings ... to show where the warning was created)
(node:20009) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20009) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Wenmoux** [comment]
更新没 按理说不会啊

**Comment by lxr760** [comment]
> 

更新了

**Comment by Wenmoux** [comment]
@lxr760 你进去脚本里看

**Comment by lxr760** [comment]
> 

![Snipaste_2021-12-23_10-43-32](https://user-images.githubusercontent.com/8476457/147179994-8e54d514-70d6-402f-b136-6fd84950a869.jpg)


我是放在青龙里跑的
