### ISSUE TITLE
求个部署到腾讯云函数的教程

### ISSUE THREAD

**Issue by liyunlongnb** [Wenmoux/checkbox#13]
大佬求个 部署到腾讯云函数的教程

**Comment by Wenmoux** [comment]
可以直接下载压缩包导入云函数的 在index.js里加一个入口函数

**Comment by Wenmoux** [comment]
exports.main_handler = () => {
  start(signList);
}

**Comment by YujiaCheng1996** [comment]
希望给加入个基于webhook的推送功能，这样方便云函数部署后提醒cookie失效。
实现大概分4步：
1.index.js中定义新全局字符串title和body，title主要用于提示是否出错，body中记录脚本中所有的关键log。
2.index.js中定义新function，输入任意变量，需要将变量console.log，加入换行后追加到body，通过关键词匹配是否出错修改title。
3.所有的脚本中需要将console.log查找替换为对应function。
4.index.js中最后用axios.post/get请求webhook，发送title和body。
之前serverchan将转型，我转了bark，其它也类似，只是换行符不同。
