### ISSUE TITLE
QL不能用了吗

### ISSUE THREAD

**Issue by TT-IPIP** [Wenmoux/checkbox#130]
开始克隆仓库 https://ghproxy.com/https://github.com/Wenmoux/checkbox.git 到 /ql/repo/Wenmoux_checkbox

更新/ql/repo/Wenmoux_checkbox成功...

检测到有新的定时任务：

Wenmoux_checkbox/wencxinstall.sh
Wenmoux_checkbox/index.js

开始尝试自动添加定时任务...

签到盒安装,手动运行一次后请禁用 -> 添加成功
签到盒 -> 添加成功

**Comment by TT-IPIP** [comment]
![image](https://user-images.githubusercontent.com/31797574/147475599-26d84ad7-707f-4388-9b55-97a36e4944bd.png)
执行完只有这2个？

**Comment by Wenmoux** [comment]
@TT-IPIP 本来就只有这两个啊....
教程都不看的吗

**Comment by TT-IPIP** [comment]
不是，我之前拉取完有很多的，换台机子和以前不一样了

**Comment by Wenmoux** [comment]
我的脚本一直都是这样.....
