### ISSUE TITLE
青龙拉取貌似出了问题

### ISSUE THREAD

**Issue by xxyyyx** [Wenmoux/checkbox#136]
![image](https://user-images.githubusercontent.com/42132468/148225027-863f489f-6d6b-4826-877b-2bbc1b3d2bbe.png)
要把ql repo https://github.com/Wenmoux/checkbox.git "index|install" "" "modules|scripts|config|Template|sendmsg"中index|install那个删掉

**Comment by xxyyyx** [comment]
![image](https://user-images.githubusercontent.com/42132468/148225205-17e0ff04-3386-4b59-a386-9f10a6c44530.png)
这样好像行了

**Comment by Wenmoux** [comment]
已更新 请更换命令 index更换为checkbox
