### ISSUE TITLE
wps邀请任务出现报错

### ISSUE THREAD

**Issue by kohyzsc123** [Wenmoux/checkbox#14]
添加wps邀请任务出现报错，百度了下没能解决 😢 
![image](https://user-images.githubusercontent.com/5027868/108799377-1ff6a200-75cb-11eb-8f24-2cf89c3bc07b.png)

**Comment by Wenmoux** [comment]
第19行function invite改成async function invite或者删掉21行的await也行 _(:D)∠)_
