### ISSUE TITLE
经管之家签显示不存在该脚本文件

### ISSUE THREAD

**Issue by chaseleaf** [Wenmoux/checkbox#143]
pinggu  不存在该脚本文件,请确认输入是否有误

**Comment by Wenmoux** [comment]
名字写错了呗。

**Comment by Wenmoux** [comment]
你要去看脚本文件名

**Comment by chaseleaf** [comment]
![image](https://user-images.githubusercontent.com/53562961/152630886-4a0318f5-5256-404d-b0f3-53d52dee64d1.png)
悄悄的问一下，大佬这个是不是就应该写pinggu 呢？就是写的这个显示不存在该脚本文件，有点迷。

**Comment by Wenmoux** [comment]
@chaseleaf 看脚本文件名字。。名字是pingu.js阿

**Comment by chaseleaf** [comment]
明白了，谢谢作者大大。重新会到github上的脚本看下，这里的名字和文件里面的不完全一样，需要以那个脚本为准。
