### ISSUE TITLE
时光相册手机格式错误

### ISSUE THREAD

**Issue by pycgo** [Wenmoux/checkbox#154]
抓包如下
![image](https://user-images.githubusercontent.com/55949132/155475193-895e680b-df76-4c34-bdaa-5709ba6bd378.png)
正常的填写手机： 86xxxxxxxxxxx  
![image](https://user-images.githubusercontent.com/55949132/155475356-d4d9fbc5-2fd3-401b-b3eb-7b1c28c60f84.png)

**Comment by RouJiANG-14** [comment]
铁汁 这么解决的啊

**Comment by geelinsir** [comment]
问题在第12行，content-length写死了 @Wenmoux
