### ISSUE TITLE
联想智选app 抓包 签到格式变了吧

### ISSUE THREAD

**Issue by pycgo** [Wenmoux/checkbox#156]
![image](https://user-images.githubusercontent.com/55949132/155693597-9c1d99ae-8d65-4834-adfe-606c1e45189c.png)

改成curl 请求大概如下 cookie我做了删减 ，大佬还能更新一下？
`curl -H "Host: mclub.lenovo.com.cn" -H "Cookie: cerpreg-passport=|2|1645781271|1961141271|bGVub3ZvSWNzQ0MTN8bzF8Z3JvdXBDb2RlOjE6MXxpc0xlbm92bzoxOjA=|AHZ3jQIxBzT4HqnWYLfE81mljU/5EwwFgyG4cxG+UmK/3se7il31i5k3sYEKEvwRa5sPt7MFisadPlZiqwAdJCoR2SUUrJaDaDP8NBa0j4cDL6Cf+5D/ti5SnVbex7sl8o1+qo3ec/RUq5pi3q86z/nOu2y7EgHIN4LbLvTReEiqSnoi5XJxRUniawXpsjBTBNtTVtR6UpurVGHpAbo7cj4jr/PiGc+zjoLEuyb7Ys7i18i8DOwsIRMayIAPZYgYUzoeNM23w7pcoSHuJaK3RUAuE5kgtBg+L1vdVZrQrptjpBQVWPKoyHBnw/9iIa0q+UPzJCU/G1fJhTWqDFtiLA==|" -H "pragma: no-cache" -H "cache-control: no-cache" -H "upgrade-insecure-requests: 1" -H "user-agent: Mozilla/5.0 (Linux; Android 6.0.1; MI 6 Build/V417IR; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.158 Mobile Safari/537.36/lenovoofficialapp/008796759182272_10222274413/newversion/versioncode-1000074/" -H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -H "accept-language: zh-CN,en-US;q=0.9" -H "x-requested-with: com.lenovo.club.app" --compressed "https://mclub.lenovo.com.cn/sign"`

**Comment by Wenmoux** [comment]
我写的app端阿。
