### ISSUE TITLE
脚本名字

### ISSUE THREAD

**Issue by 3418359665** [Wenmoux/checkbox#161]
4399和猫耳运行不了
![Screenshot_2022-03-12-14-35-21-57_e39d2c7de19156b0683cd93e8735f348](https://user-images.githubusercontent.com/86676694/158007099-d0482181-b6b8-4dba-b68f-24b58b2fad7e.jpg)

**Comment by Wenmoux** [comment]
让你看脚本文件名 你在这自己拼写呢

**Comment by llh1347** [comment]
路过

**Comment by 3418359665** [comment]
> 让你看脚本文件名 你在这自己拼写呢

我看的是这里

![IMG_20220313_121249](https://user-images.githubusercontent.com/86676694/158044745-fd7a3b3c-80f2-4024-9239-d4c2c516b110.jpg)

**Comment by Wenmoux** [comment]
@3418359665 没人让看这里阿。。
