### ISSUE TITLE
多看阅读的好像不能用了 

### ISSUE THREAD

**Issue by cachexy123** [Wenmoux/checkbox#162]
重新抓也不行,你们还能用吗

**Comment by Wenmoux** [comment]
@cachexy123 那就是抓错了

**Comment by cachexy123** [comment]
> @cachexy123 那就是抓错了

我之前是能用的，昨天突然不行，看看日志，他给我报的是xsrf token错误，

**Comment by cachexy123** [comment]
> @cachexy123 那就是抓错了

![IMG_20220313_181047](https://user-images.githubusercontent.com/44692789/158054729-9d6e1ab7-eb59-4aea-92f0-77293cfd1666.jpg)
