### ISSUE TITLE
云函数运行报错

### ISSUE THREAD

**Issue by forchannot** [Wenmoux/checkbox#169]
START RequestId: cb6e3aa0-81ca-4181-bb05-c1f0dc6ce2ab任务个数  1
------------开始签到任务------------
任务1执行中
{ code: 1, msg: 'CLIENT ERROR' }
------------任务执行完毕------------

【NGA论坛】：CLIENT ERROR    

Response RequestId: cb6e3aa0-81ca-4181-bb05-c1f0dc6ce2ab RetMsg: nullEND RequestId: cb6e3aa0-81ca-4181-bb05-c1f0dc6ce2abReport RequestId: cb6e3aa0-81ca-4181-bb05-c1f0dc6ce2ab Duration: 171ms Memory: 128MB MemUsage: 17.47MB

**Comment by Wenmoux** [comment]
更新 增加user-agent
