### ISSUE TITLE
时光相册登录失败

### ISSUE THREAD

**Issue by RouJiANG-14** [Wenmoux/checkbox#17]
是用的腾讯云函数，WPS的签到和多看的签到都可以正常运行。
config里时光相册填写手机号和帐号密码，核实填写正确，但是日志反馈：登陆失败账号或密码错误
网页登录everphoto.cn，点击登录跳转后一直提示在加载。
不知道是哪里出现问题。

**Comment by Wenmoux** [comment]
抓包登陆时候的参数 不是直接填密码的 手机号貌似也有个+86

**Comment by RouJiANG-14** [comment]
可以网页端提取参数么。？手机不想再装app研究了😂😂😂

**Comment by Wenmoux** [comment]
可

**Comment by RouJiANG-14** [comment]
那我研究一下🌚谢谢老铁！！
