### ISSUE TITLE
请求增加终点论坛签到

### ISSUE THREAD

**Issue by Dimlitter** [Wenmoux/checkbox#170]
主网站: https://bbs.zdfx.net
签到地址https://bbs.zdfx.net/k_misign-sign.html
签到api : https://bbs.zdfx.net/api/qiandao.html

因为自身能力有限，只能勉强写了一个selenium驱动进行签到的脚本，但是自动运行根本拉不起来。。。
希望温某大佬能解决这一问题，谢谢您！
> 签到post请求里带的token我一直找不到，且api签到需要通过滑块验证码
> 我自己搓的脚本链接：https://t.me/viiberdaily/127

**Comment by limoruirui** [comment]
都关闭注册了

**Comment by Dimlitter** [comment]
> 都关闭注册了

手机app能注册

**Comment by limoruirui** [comment]
https://www.recaptcha.net/recaptcha/api2/anchor?ar=1&k=6Lfl9bwZAAAAADZ5gAwWyb7U2UynEMHR52oS8d9V&co=aHR0cHM6Ly9iYnMuemRmeC5uZXQ6NDQz&hl=zh-CN&v=gZWLhEUEJFxEhoT5hpjn2xHK&size=invisible&cb=nq1ea2f7mjdm
get请求这个 返回的html里就有token

**Comment by limoruirui** [comment]
试了一下 用这个得到的token 请求签到api 返回的是今日已签 至于能不能成不知道 没号了 注册太麻烦

**Comment by Dimlitter** [comment]
感谢提点，我说呢，抓包到的网址中间怎么夹杂了写奇奇怪怪的网站

**Comment by Dimlitter** [comment]
再多问一句，这个get请求里带的cb参数在哪啊，这个参数会发生变化，但是只在 https://www.recaptcha.net/ 这个网址中存在。
> 能给一下您的联系方式吗？谢谢

**Comment by limoruirui** [comment]
> 再多问一句，这个get请求里带的cb参数在哪啊，这个参数会发生变化，但是只在 https://www.recaptcha.net/ 这个网址中存在。
> 
> > 能给一下您的联系方式吗？谢谢

这个我没去看 我看到是变化的 但是试了一下 随手填几天位数一样的 也正常返回结果 然后把得到的token拿来请求 都是今日已签 因为我就一个号 刚刚试的时候手动点了 再注册一个太麻烦 可以签的话就不管呗 直接随机生成位数一样的就算了 明天试试不可以签再说

**Comment by Dimlitter** [comment]
@limoruirui 能给一个您的联系方式吗？方便交流，issue里面讲太麻烦了，有些关于session的隐私也不太好发，谢谢！

**Comment by Dimlitter** [comment]
我用postman发送的请求返回的是这个, www
- 您当前的访问请求当中含有非法字符，已经被系统拒绝
