### ISSUE TITLE
这里是不是多打了一个易字？

### ISSUE THREAD

**Issue by BillScott1024** [Wenmoux/checkbox#18]
日志：
![image](https://user-images.githubusercontent.com/22955480/109744939-1b0aa180-7c0e-11eb-8f74-6f7d13b13579.png)

**Comment by Wenmoux** [comment]
交易    🍌易 (๑•́ ₃ •̀๑)

**Comment by BillScott1024** [comment]
哈哈好吧
我在加推送信息，发现看不懂这句 log
![image](https://user-images.githubusercontent.com/22955480/109748782-6922a380-7c14-11eb-926b-d735a36cd83f.png)

**Comment by Wenmoux** [comment]
发现看直播60分钟领扭蛋那个也能一键完成
但是要手动看30s直播
没看到时间包是哪个
ヽ（・＿・；)ノ

**Comment by Wenmoux** [comment]
加上去了 我测试可以
![](https://cdn.jsdelivr.net/gh/Wenmoux/wenpic/other/IMG_20210304_001838.jpg)
