### ISSUE TITLE
是否可以失败再推送？

### ISSUE THREAD

**Issue by lazureice** [Wenmoux/checkbox#183]
RT。现在是所有结果都推送，可以只在签到失败时再推送通知吗？

**Comment by Wenmoux** [comment]
过几天改 (虽然可能不能全单独推 写的太乱了之前

**Comment by lazureice** [comment]
需要改动很多吗？那不改也没关系。
我暂时的解决办法是写个简单的 crontab 任务查询日志是否含有”失败“，有就调用tg url发消息。就是有几个签到脚本不会输出”失败“，只能暂时修改脚本添加进去。

**Comment by Wenmoux** [comment]
@lazureice 我就打算这样啊。。if(msg.match(/出错|失败|失效|cookie/)) await sendmsg(msg) 大概这意思
