### ISSUE TITLE
佬，起点读书cookie是抓那个包啊？

### ISSUE THREAD

**Issue by wsdjj** [Wenmoux/checkbox#187]
试了很多包的cookie都参数错误
【起点读书：】
  签到：参数错误
  投推荐票：参数错误
  比心：参数错误
  抽卡：参数错误    

我是这么填的不知道是不是有问题
qidian: 
  cookie: QDH=q6WlYjtlrL8aNKdeKpvRleXGTkIFY9AT4I4yls3qC6xO1ZRBk1AQQibOz74dX9+6F3T7OOZJBxLcYzwBJv2QLv/tMjljxJ1+ZBWTQzC4b97qLnKzuYBzay5//FQc44dAkq504aKJk/uo+og85awueEDoBNALVwP4QZPYoTyRfObW1VJ55iEC3WscI8zq514bWeemHrIadJ4n+Cfm56SRLyJK9jYfPRl1SuzJXFZK+ttSKbg=; QDHeader=KG51bGwpfChudWxsKXw4Mjh8MTc5MnwobnVsbCl8MTQuNDB8MHxpT1MvaVBob25lLyhudWxsKXwwfChudWxsKXwobnVsbCl8MjE4ODE3NjA3fDE2NTA=; _csrfToken=EwzEumwqyhIakRVOcbxoHR5REx16b7GpEqjBSXo2; _ga=GA1.2.1096019361.1650446781; _ga_D20NXNVDG2=GS1.1.1650446779.1.0.1650446850.0; _ga_VMQL7235X0=GS1.1.1650446779.1.0.1650446850.0; _gid=GA1.2.2103588307.1650446782; appId=12; areaId=40; bar=88; cmfuToken=N((b8giJqDzjCxtMwmOLYjTmEqItzqCK30l7TZieWa_t5f5cJnqlo7PiUj8PKDEc8N3e2tegNy1fWRkiUfdGBJCw4Efv2mrtc7vSEevMsq6rlgbHIXXhHlilm9kbEVKM94T64qfpe__wJA_zvuYT3C-JIdlQXXZY_2o54dnZ5_aUWHvmuPtKMseWAwx72qtZZASCsHRsPKuwgs16iP5IM1; e1={"pid":"mqd_P_yueli","eid":""}; e2=; fu=980257451; hiijack=0; mode=normal; newstatisticUUID=1650446776_1285842948; qid=079c2f2c-6215-45b5-b77d-97f4ca4438dc; wal=1; ywguid=800218817607; ywkey=ywOCaMfbLPkD; ywopenid=7BA0A654D4B8FF5D4C418E97151137E8
  UserId: 218817602
  deviceUid: 079c2f3c-6215-45b5-b77d-97f4ca4438dc
  BookId: 1030882891
  TicketCount: 1
  roleId: 
  version: 7.9.186

**Comment by Wenmoux** [comment]
ttps://druidv6.if.qidian.下的cookie
我感觉你的不太对劲

还有deviceuid好像也不对 不过无所谓

**Comment by wsdjj** [comment]
找不到druidv6.if.qidian网段的，我抓的是iOS端起点读书app5.9.206的，是不是版本问题😭？

**Comment by Wenmoux** [comment]
安卓 /狗头

**Comment by Wenmoux** [comment]
ios不清楚

**Comment by wsdjj** [comment]
刚刚用模拟器抓包成功了👍没有问题

**Comment by xhpk** [comment]
> 刚刚用模拟器抓包成功了👍没有问题

大哥用的啥模拟器，啥抓包软件
