### ISSUE TITLE
多看签到需要修改哪些参数？

### ISSUE THREAD

**Issue by xiaoyaoyuxin** [Wenmoux/checkbox#2]
好眼馋这些脚本，但不知怎么修改，不知能否讲解一下，不胜感激！

**Comment by Wenmoux** [comment]
填进去cookie就行
配置好node.js环境
然后node xxx.js就可以运行了

**Comment by jorzen** [comment]
cookie怎么找啊

**Comment by jorzen** [comment]
这个不能用auto.js运行吧。
怎么操作的，能不能说得更详细一点，谢谢。

**Comment by jorzen** [comment]
报错：TypeError: Cannot read property 'map' of undefined
    at C:\Users\mac\Downloads\checkbox-master\src\duokan.js:49:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
//体验app
function getids() {
    return new Promise(async resolve => {
        try {
            let rest = await axios.post("https://www.duokan.com/growth/user/task/list", `activity_id=1124&all_required=1&${getc()}&withid=1`, header)
            rest.data.data.map(list => {                         // 报错显示错误出在这行，但很可能是上行rest返回的值不对
                ids[ids.length] = list.task_id
            })
            console.log(ids)
        } catch (err) {
            console.log(err)
        }
        resolve()
    })
}

**Comment by Wenmoux** [comment]
cookie抓对了嘛  比如查询豆子数量成功没

**Comment by Wenmoux** [comment]
或者推荐使用dora.js(安卓app)群内有对应多看阅读插件 (直接q群搜索dora.js就能搜到群

**Comment by jorzen** [comment]
> cookie抓对了嘛 比如查询豆子数量成功没 @jorzen

查询豆子数量成功了，体验app没有成功，发现是getids（）出错了，得到的任务list为空

**Comment by jorzen** [comment]
> 或者推荐使用dora.js(安卓app)群内有对应多看阅读插件 (直接q群搜索dora.js就能搜到群

下了dora.js，怎么找多看阅读插件啊

**Comment by jorzen** [comment]
> 填进去cookie就行
> 配置好node.js环境
> 然后node xxx.js就可以运行了

填进去的cookie是安卓app里的，还是电脑网页里的就可以了

**Comment by Wenmoux** [comment]
安卓app里的 话说你的设备是非小米的吗 我没测试过 但是有群友说可以  你把ids手动改成[1796,1797,1798,1799,1800]试试有没有奖励 @jorzen

**Comment by jorzen** [comment]
> 安卓app里的 话说你的设备是非小米的吗 我没测试过 但是有群友说可以 你把ids手动改成[1796,1797,1798,1799,1800]试试有没有奖励 @jorzen
改了之后还是不行。我用的是小米6。请问你是怎么抓取到安卓APP里的cookie的？

**Comment by Wenmoux** [comment]
@jorzen  那就不知道了 你手动做任务看看有没有任务

用httpcanary抓的

**Comment by jorzen** [comment]
> @jorzen 那就不知道了 你手动做任务看看有没有任务
> 
> 用httpcanary抓的

谢谢，问题解决了
