### ISSUE TITLE
nga 签到失效 ios客户端抓包

### ISSUE THREAD

**Issue by Hellager** [Wenmoux/checkbox#203]
如题，uid, token, ua 正常，app_id ios客户端的抓包会是1001，已改
签到执行返回 407 client error，res.data 是个 html
尝试补全表单或 headers 无效，尝试用 qs 序列化请求数据无效
暂时还没试出来应该怎么发送请求

**Comment by Wenmoux** [comment]
安卓端的

**Comment by Hellager** [comment]
查明白了，post data的格式问题，和平台无关，没想到坑在这里

**Comment by Wenmoux** [comment]
(ฅ∀<`๑)╭格式 。其实安卓也不是我写的这种 
估计和ios一样
然后被我改了
反正好了就好

**Comment by SekiBetu** [comment]
NGA的签到是只有签到吗，那个看视频的和分享帖子的签到是没的吗
