### ISSUE TITLE
可以申请一个论坛的签到么?

### ISSUE THREAD

**Issue by BillScott1024** [Wenmoux/checkbox#21]
论坛地址: https://www.diygm.com/

每日签到奖励是金币

自己写了一下发现获取不到签到成功失败的状态

**Comment by Wenmoux** [comment]
https://github.com/Wenmoux/checkbox/blob/d679082077e93264d4a2b8a2737e046cc4fe9b2b/scripts/diygm.js

没测试 就试了今天的
有问题再说
里边有个东西忘改了不过问题不大
下次更新改了

**Comment by BillScott1024** [comment]
谢谢大佬，我加进去测试下，有问题再来反馈

<iframe src="https://codesandbox.io/embed/nameless-grass-23m5d?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="nameless-grass-23m5d"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>

**Comment by BillScott1024** [comment]
测试了一下可以签到成功，但是Template.js 里的resolve 返回值是 null

**Comment by BillScott1024** [comment]
把 resolve 改到 trycatch 里面，可以了：
![image](https://user-images.githubusercontent.com/22955480/110757707-a75c3a80-8286-11eb-84ff-c42cd98c1139.png)
