### ISSUE TITLE
请问起点读书的UserId和deviceUid怎么抓

### ISSUE THREAD

**Issue by bpefei** [Wenmoux/checkbox#219]
看了请求https://druidv6.if.qidian.com 的包，只抓到了Cookie，没发现UserId和deviceUid，请问哪里才能抓到它们呢

**Comment by bpefei** [comment]
没事了

**Comment by 17huiwei** [comment]
https://druidv6.if.qidian.com/里面，我还是只能找到cookie

**Comment by hfuulzy** [comment]
别没事了呀。。。我在包里也没看到这些字段。。。

**Comment by Wenmoux** [comment]
笨方法：直接开启抓包 和个人信息有关的界面全点一下 然后搜索关键字
