### ISSUE TITLE
[BUG 反馈] ACFUN,传奇论坛签到和CSDN奖励

### ISSUE THREAD

**Issue by BillScott1024** [Wenmoux/checkbox#22]
**1. ACFUN的签到任务, 投香蕉和直播开扭蛋无法完成的BUG有考虑修复么?**
投香蕉随机生成视频的id 好像不太行了
直播需要手动看30s...,不知道能不能实现完全自动

![image](https://user-images.githubusercontent.com/22955480/111016521-721c2d80-83e9-11eb-8c78-c71a79810f91.png)

**2. 传奇论坛签到签到成功,但是没获取到正确的成功返回信息,log里打印的是空白的**
不知道是不是正则匹配出了问题
![image](https://user-images.githubusercontent.com/22955480/111016583-c3c4b800-83e9-11eb-9ef8-17cb0a889e36.png)

3. **CSDN的签到返回是object,没有解析正确的签到奖励类型**
我加的推送暂时直接就JSON.stringfy一下了...
![image](https://user-images.githubusercontent.com/22955480/111016596-d808b500-83e9-11eb-96dd-839860fa82e2.png)

![image](https://user-images.githubusercontent.com/22955480/111016566-a98ada00-83e9-11eb-88e8-733edf23648e.png)

**Comment by Wenmoux** [comment]
csdn嗯 我懒得加当时 
acfun 确实需要手动看30s才行 至于自动看有个sign加密的好像 没咋研究 
传奇那个我已经知道了
🤐

**Comment by Wenmoux** [comment]
投蕉那个是没成功吗 不是循环了三次 那个交易成功 我回头瞅瞅

**Comment by BillScott1024** [comment]
> 投蕉那个是没成功吗 不是循环了三次 那个交易成功 我回头瞅瞅

投蕉不太清楚有没有成功,没查到记录

坐等大佬修复

**Comment by Wenmoux** [comment]
看看每日任务里完成没 就知道了
