### ISSUE TITLE
刺猬猫增加了看广告给书币的每周任务，温佬能整一下吗

### ISSUE THREAD

**Issue by 3054528216** [Wenmoux/checkbox#221]

**Comment by TaskaTang** [comment]
都是些什么不知名的软件

**Comment by llh1347** [comment]
> 都是些什么不知名的软件

呜呜，大佬，能帮忙写一个支付宝自动刷余额的脚本吗？求求了😭😭

**Comment by limoruirui** [comment]
@llh1347 uploading AlipayCrack.exe

**Comment by TaskaTang** [comment]
> > 都是些什么不知名的软件
> 
> 呜呜，大佬，能帮忙写一个支付宝自动刷余额的脚本吗？求求了😭😭

我看大佬都删库跑路了

**Comment by Wenmoux** [comment]
@TaskaTang 删库了你评论的谁的

**Comment by TaskaTang** [comment]
你自己看看主分支上的情况
________________________________
发件人: Wenmoux ***@***.***>
发送时间: 2022年9月8日 20:12
收件人: Wenmoux/checkbox ***@***.***>
抄送: TaskaTang ***@***.***>; Mention ***@***.***>
主题: Re: [Wenmoux/checkbox] 刺猬猫增加了看广告给书币的每周任务，温佬能整一下吗 (Issue #221)


@TaskaTang<https://github.com/TaskaTang> 删库了你评论的谁的

―

**Comment by Wenmoux** [comment]
@TaskaTang 你都知道分支了 还说删库了 😕
