### ISSUE TITLE
请求添加盒子里脚本间运行间隔时间参数。

### ISSUE THREAD

**Issue by shengmean** [Wenmoux/checkbox#224]
RT，请求添加盒子里的脚本之间运行间隔时间参数。现在是快男模式，滴滴滴，就完了。。想要滴。。。。。。滴。。。。。。。滴。。。。。。这种。

**Comment by xuexijiaoben** [comment]
百度一下cron表达式，看一下就明白了

**Comment by shengmean** [comment]
我的说不是签到盒本身的定时，而是签到盒运行时，脚本与脚本之间的延迟。。比如爱奇艺和联想两上脚本之间的延迟。

**Comment by shengmean** [comment]
> 百度一下cron表达式，看一下就明白了

我的说不是签到盒本身的定时，而是签到盒运行时，脚本与脚本之间的延迟。。比如爱奇艺和联想两上脚本之间的延迟。

**Comment by limoruirui** [comment]
@shengmean 写两条cron 一条爱奇艺 一条联想
