### ISSUE TITLE
请求增加哔咔漫画的签到

### ISSUE THREAD

**Issue by wsdjj** [Wenmoux/checkbox#229]
是登入获取token，然后用token签到的类型

**Comment by LinYuanovo** [comment]
@wsdjj 有同类型项目了

**Comment by wsdjj** [comment]
> @wsdjj 有同类型项目了

daliy大佬的吗，那个没有维护，已经不行了

**Comment by LinYuanovo** [comment]
@wsdjj GitHub一搜一堆能用的啊

**Comment by wsdjj** [comment]
> @wsdjj GitHub一搜一堆能用的啊

https://github.com/qq332374857/BlueSkyClouds-My-Actions/blob/master/function/bika/bika.py
不会啊，我搜过了，除了daliy大佬的，就只有这个版本的了，一样没有维护过期了
比如脚本上的pica_api_host = "picaapi.picacomic.com"，现在的host是api.tipatipa.xyz了

**Comment by wsdjj** [comment]
而且我抓了一下登入包，登入的加密好像不一样了
![605F66BF-9D2B-42E7-A424-74579E2A71D3](https://user-images.githubusercontent.com/76938752/191378931-1c8f9436-6b63-47c8-8209-c6bbb496cf33.png)

**Comment by LinYuanovo** [comment]
@wsdjj 去找一个C#用Github action的项目，我一直在用

**Comment by wsdjj** [comment]
> @wsdjj 去找一个C#用Github action的项目，我一直在用

青龙可以跑吗，我的几个号都因为跑了action被封了😂

**Comment by BlueSkyClouds** [comment]
不影响啊  虽然换了host但依旧能用

**Comment by wsdjj** [comment]
现在host是api.manhuabika.com，改了之后还真可以跑了😅

**Comment by BlueSkyClouds** [comment]
> 现在host是api.manhuabika.com，改了之后还真可以跑了😅

可能是跟地区解析有关 旧版的host一直都是可以用的 重来没断过
