### ISSUE TITLE
联想智选登陆失败！无法获取token，青龙最新版

### ISSUE THREAD

**Issue by yeli008** [Wenmoux/checkbox#231]
大佬，我用的青龙最新版，yml文件里面填了cblist只填了一个lenovo   下面的账号密码和baseinfo都填了，运行checkbox程序最后提示联想智选登陆失败！无法获取token，大佬能帮我看下吗？

**Comment by yeli008** [comment]
![Snipaste_2022-10-06_09-51-35](https://user-images.githubusercontent.com/66049634/194196685-f9b83e81-5926-4fde-aacc-843198cc5802.jpg)
这个是图片

**Comment by qwasddd** [comment]
是不是脚本没更新，我的之前也会这样，后来发现脚本更新出错了，手动更新后又可以签到了

**Comment by yeli008** [comment]
脚本我都是新拉的，不是更新问题

**Comment by qwasddd** [comment]
要不就试一下只填账号和密码，反正我这样就可以签到

**Comment by yeli008** [comment]
只填账号和密码也试过了不行
