### ISSUE TITLE
阡陌居，书香门第，fishc签到出错

### ISSUE THREAD

**Issue by longwangjiang** [Wenmoux/checkbox#245]
阡陌居，书香门第，fishc，这三个签到都出问题了。

## 开始执行... 2022-12-01 21:00:00

当前是青龙面板,路径：/ql
建议更新到最新版青龙再来运行哦,或者手动修改路径叭~
任务个数  3
------------开始签到任务------------
任务1执行中
去签到
��TMoG>����D�e=6-Z���HN���xw��_̌ㄪ��Tj V�"E��d����\8���K��3��"$������<��3ޥ�$�M.����U�xd�H�
2��"��sΛou����i�m\�,7�8�^����]�X���k������d}s@6J۫H�u�R:�+c�29J*��2�Nb!�j%�!1��]9q���1�
E�z�z+�Y��k�J��Rfң�Y�J�f��~k$6�������m�@P�D�-M�f��I�u���U�<)Kx��w�t{�f�����V���jw���t��������ڤD+����(Y*J�,�y��������Yps(�Q:Ag҅q$4ǐ�]?�u��E�,#&ar(R�u�Yh����|��Pڱ�.�Y�,��p�ؐ �,������l�H�-,"X7j�\��w�6��-��ŋ�X�ť�!�b���U��"`��b1ĸu��ˏm0��
=j|��dU�x��հ_Ĕ�K�-��[��"����ʀfhlə�)��H|Mb%������"9��j�j�AKx�z�f}�P��t5�*�U�kk܋�A��3�ri��e��~����"����o��*ݞ���mg����
��[/���m���=a��x��)U
b�o-�*�����?��a�(k�9o����?|7ٙ�69�{x������d����w�9ޛ��y�t��/wO�>�u�������N=� �"���lVg�����K4������m��"�\]e>�>�}}�v���������{v^�<���f�x��bV�V�4���C�����A�,�
签到失败!原因未知
签到失败!原因未知
去申请威望红包任务
�璠鹲Wv���赸Y峊栨)	4姨F`� �LR┅烆灆耳Ew蠈勫?&v懋鉼�<孻蟀�d屫u�?l直譹6U┶�)SN�;鬓铋执$d珚囚睇8鬈s香;Ё灈�鶠�圇J��2ッ荿8x`�$忎r荎{r归賗楗��3�B6/蛕婍佱貖櫵�=$Kr+躵.醉v齿R竹毠�#箉毇@兣蠎 62�歕荼}姯8o櫠_I櫑011羾笪孩� K��#�啥雪葅;许`dv琳eI錙9戌��0)�-朋鯛椰仙R�&	尷垣��竧y��{疘#掫�譕_~坃S9�r泅p1[濒�<�/tO骳K埳E紦��猤改�X縜>y鳓n霝8^�蟠岖鞸螴/暡毗J;h�v熣KRlM阢X緉煉�惃�
誵<Ｙ
b�簌翲1_(E�豭�焯眩栤矹�?扉褒0Xk赝豛砠缋剀wV3Gg[亥僃W	尯?�:x藛�_梈炥H圗!熛煷�猛Q�)影�$O7+�,樅咭ul)€埫W}L颧褦@嫂娳襰瑂璓��巈9v絶�.磙�)[帴�艧K淌E"N偎JG岘r担x已��槚*R�P�銀黛�=菐�?���碳8}郒�桶敠炪聋扣{d�睿��v�!��貵兤劔�64綱�8N�g涡]O�苲醥徴妳R�窖K1lz匐�-j 颤栍m�骇*�6�6%uN�6�洊焙b歂穉:J@嵍�
p@奆髗篺秲讲吪;�w玳鈖q裎繙y�8\Z|魈角嬅��炐��_^~��+��8<緓岬ク椌_�E魡�6v虃�#{��痊`Р�H^漹:KZI[潫欈軺忕蹥ev[濟馽m跖V鱬毙��锽�腒嚰焂G:噺Y8駫j)�11髬JK=0籛�S�19E煙=納�IL�>}庑顧鑼3揝9.$�B`|O�缺QB`_�擊�<�'奿&舥MC�$9�楠貐]K;Y~|P�8f`笡囯聂湟��&�遇孞:�幾恫n藵4犝组(nH�6潢u?媋B，罳函費�3租F坱敚-H哣戫N崷�M艊!s汱葤c胐hN桩菷c�)�,Z�8歗�wAwm蠔婇霌唐iF囃	倦禫s冧闠/�椒/+骫fV斂�
啪荕虇geuCP�V丸ヘB�7^礈翵昂L%[�!t*?�璪9u兇xui邂wЭ準)綆=�,O���B鐮�鮜?8鍮w
fG?F
b炈�!服|鱉挃膜辇阌+毝O�8�鑳A损矰霭斸b帣W駗檠龠煿�鑢b櫮&峄虣�隦�瑁邋���6E憠妱棻�	崼t絒塼l曗5釚鹊簤�Υ*碴槑W栮&iu�蜜O峡��k�q崏sx2精�鷢鎀��,W�>8�8扻�5跰胒SC<� 鼎貁檦�=k炟HW'O{qLm2悲[_輝B�-幢壃��甼3�7]
J�
蝫ě77A堩搇呡)縦j�疉絺�€F�8挺┛@=�
a忎/V�+o~�走奖蜉卥w棦�煾顰;c梭{揬璆R仔��q=�3�<g这7�/^<槭_N筳i>A调^,檀X�?Z�&c壍鄗鹉倸ホ頌�筆 �,耭沪睵杔�Z�4zw<]s��b箵F)-鞿5;P�U阷殲佣�Owuc;忡�{�:<�(Kyi,�h�)輮T/�
っ'通[調O锝�,�橤縄�9,倆��{i�妻咽付忒|6X鶴梭K,V缇�卛�t+A颮嬣0溈s铞楋Na6;鋾wR��+牘�
�M垴�熡4b&`崑盼]闪Lb,軡滦d*p�6業萞�w�>��霦�4饱腖釾c<澥低搁<I矞"幸z嶜 4唈"掚`橫蔍O踷Lw歚3鳏荟塘t栶bPv�洬V虾vsHz伟\��藁鲳~�	S沪=�秵X钊�{�殂嚊#6E�罚鋜	{�?€陕<�QB�>6+柈)嬷P搔J#颃o}�汰�傴璥(蛿F橥G+芮鷄虒n�4g嬑濵旻雲晎�
甹肍秱璴�4Z呖襻鸞Ak冰謵J3�Q�羅�z�?6Gk娹�"橩濬e鋖�乳a罺渙d���:Q�琟沐跺&璣=�鯄�1�F乨嬅�u���4/1Q�笐�股P∟VSb(F簺劝
�礰祪;隲14矓+庘譞�4:滄T^/祩�+_*�5�%臘�"u澈W戵與��営m8I<�跿:亜� r陀蒏盉鋥An*��3L惥�( k�5郻菟餋辞"╤鼆o溡+九頬H7�燠�\��媳涐蓆�0�?氣緪S6蠵鋡逖鸰萓雟基瞾8;91DU虈t
 钫E酔�鑈漆��`菴嵌@�X�
吞A|%�瀒h�2\E檡曫"惃y&"烏HU`服紃m�'c喺忇�9
O秚G崧躱玑V鑡GG�0詵亗i�>7<+颍`馜懬
L"�$`vu巘�."< G�
�"邱JMGxy�﨧/2�
K嵍�铝!闀t�
g�6�(铓)梌偓D璩埆�[u漘M俲嘟雋2.r垝殰v繸牏瑬夥*粩馬┊邋隄O锡/棡][�嘃�.刡�
G临頇?V
�懷�
)棫荈�,8(繃A暝拽矧U/~a��(a鄸_猵?�犂€塇持v-妙ˉk▊摧s洖㈤嗇p嗕昝k��氩袋С鸥�]y皥?�宨a�轇�c4欒��9訰衡┉�xj鯋f{豯B猖$)xR電W�GY 邆屔€1€&�从5�椔i4��砗e蓝鵯鶀広鲩f鴏朻>�!`�):1陈麐�擪[/Q嗧�憠B<�镠S蛱%D�_�=v �!%I_{嗮jD恽+鲁zk弰嬓�lF4扽�
艚VxH&3�腩LGUL#@�+6GF綷鎴=O
+HKJ猲�q@0穫瀅 蒜欀	<霪]�饎jHo�.�3b陯燶r�	皧3偛葬06�#�觅"Jo|臭磐o>��煞�?基y�籼o���仴jK�憃颁y掂z笻敟"'w鼟尤箢<�1邉��!��Eg8肌Ar	j怭#I�怕w[櫠式弔怆丮碬ш� pl!贮D<e�(l�1c�4<S�+瞽kK�
HR��4髀暲匁憱来;堿狃y�(望E故�覶�滰帇M. 1�#!�譩?\+繷!t@\輫d��& �$L荝逄艓hV�粀�D逞び�妲C鄵圙智駑l7l#8蕩匂$�嗔�2膫^4�
眖�5�袳妱F溎�(偨.3敋躀<v薥叛��蒤欢��鱵#O:v苁癍d�*篷BatbW譙*斊鶬ir�'赒Bg蚑垉ǒ	���犟氓疻>~�恁坨nGlKz勼,鉌劎-€�8河G狆�_`貜Te
筚�%t雥饄寴CymbbM6FP2q�鵰�4郐L稬�ゐ�/'V今乡/�s銹Q�緊�%\喻sbu*畓箢]炵媊€P�)c
裟��P`��<眛樯蚾蒣Y^巨g弗g�#��屜羹I�闶毣塏r�1冻闯�傚 ?�粉鏥~w齘�怨偭厛�u'h誘�$裘掞)g�唒訕嬜鸧R�R�+T枙byN�o吺O$冷��-��n墩�蝽输讑兴�◎S諸金陧э/=d內JI壑�4逯U&妤婽絭彐�U7称`⒏鶊�*�:J州w2嬝Wv笆+帣尘欤8#�

捜S鞚J鮥堠韬�%亂売�p�-崥J窹詰盜鱹hh頶夰S鱾4乕}髯魑^�铛疯�?�钪豢后熺n浸瞩�.齠檠鵎椢\}r鐛�7_肫7廮{痫g縙z磣蕷暌��*瞓硢�#�敾�);�,y�t耙�扞(m襊剒T4程�<,昉鷸Hu矦3d�<f7�枓k烧沖禁酊w绡褊玏?�鲒艊藦?}绶窡<f{?��嬤君�o_��"p%烡d糗菻�	%<�4%o玆Sm^蔠戙~諨謁Xz鷯F[WM菄I環ㄨ驪O	嵗沲&aZR沿薢丷捗耶馫b,驨y蓖!T鏳偻蠆媉蓯O憠�5酼�0来2$�奦�6
Dw!如畐HT��滲嶃犋m
磻暅圓���箏襍i/,遘��饇X��賰Mq:�幐奵偃彨q詖/5
r��G"柒俄s�:/衩j�
黍囿苗认憹礊匂熵NE憗骲�D�h>
@�xwQXu0揟青|[鉸馌滷�
�8_臺ZK翜!匶*硎b航&JU砝a醍嘝�6楺�(�5H�屖O覕�dM輓璉泫鐕@?
緮0�慺�瀬 �}�;m徑僞埥�wK-駪�唄1諻纒TM�=m~M.�6唙�*鸆訠A<�.y炔芕1M�f迅蝪袍57,�#>�
嫥籩�:O��q脪@w&+r趁珖\RS�1p2�=蝨;0L郧��﹝
l�#�<€€J纟�*弹"眚渭�.�3€黹#EX(减燛�慌�4c��%+鼅0]I/抶3 �,驇4Twy巸�春麿飣v黧岺冹u裰~E视F\鍓)vl半�;�哄淤�'檰�d蕮�?"g�"�W聕收O�跗�3�呓z缟Ｋ熅s鯖+稞姲�0#杅,耰櫼f*�%H媭鰛*垴�9�腚闐鷯茀[q乨Q閗�Re銗{駶勡#回
靕啀謭9;n�3僙窳Wd�9|燲綷~E鰥rY.钴匟a|�<,�
<�<诎V枊貌爫殴貌メ7嬛唀讝藚a�銲4�y�$彾芦�2妹ud9�懬韻軈yx龓�/翁>縦XB⒈8R��X(迄m#WB与恵竎�皌豷Tx懞&�>�-銴參劽rP �#SQ�)漧�(竹wl�2礐C?仳��
l搼U=靦uD<R}A@S猚 勑f�7$贞4�\$!�j猹酏珌T$�0@_丩�醱��>鑱扔�$��聓膚&簟_椒賖笋弘~dBuq鸔8喔�3B*
O繢恆煒如瞧岵<C�{,*d琚�=��(b媴夒{8唟坿�/0艍�?�'躥)�O泛牊綨�Q
Q櫩橺趱i�&�5F&煪e鳢^
27]矄锓]睱冘=�6仪q亦[Yd弦鞰�賀錻蕡艇苅彦蟔�6s矣缅摅雘]�瘺考蝣暦O遙K:韷喝蚽�鎁g疾瞣�董�2SB檋oc擺碹V覜塺Z▎�藹瑔楬�刅辄胚矿顺W牌, 弩�:凈���NP�脠暾b�"h垟澙��挑葋�${枺瀠軆€O �T;S�4;镓緈鄱�)\]逐�
抈玃Q�*(�>絣阭,羭d鑋炐�-挅]蘥�髬嬏�-K�=宓X,鑵馫�4緆bWc讟ZSFU�4憻�9��/3怹ⅲ~迁奧�3�郉dU;锹1蕠慳焩暵���8{v�仂兢澫Q烀l�&��*'�:
申请威望红包任务失败!原因未知
申请威望红包任务失败!原因未知
【阡陌居】：     签到：签到失败!原因未知
    申请威望红包任务：申请威望红包任务失败!原因未知

任务2执行中
去签到
�昑MoG>�脹墇藌l�Z�來圚N鑡�;鰩丿螌銊奯脜HM墪�塇VA
!Hp酓�\窪粢wf7"$烀祆误<镒3蕙�$哅.暼�︰�xd�
2��"逛麔7哧6{?!�X鄹襓nq(絨ym┗颈Bi倹W{+X生"鎬l敹W	怘胲<W�,dr擳294篹澞Bj認–b蚚籸�:鏸�剨侸�%� 鏛橼兑<伓敊鬶q襚�F瑂��4�
姨R蚐眙秙N (v
Ⅸ枽F�A膜夂Q�詊[灁%糀只W航k3卣铗j珆sq祷皂t�7疳騴箨蝓6)袹oc54J朖丷&�9o辯p間�6�}�蔿攩N惻檛a	�1讖馌� b３漞�$LE闎�9M譢笎o�!J;V貐4K懪��r臑窥�䴕�i偞匛�腈B瓥kZ�>譮~B柌E`R皒K暎��:D\#<}侣揨,vX,�肺騻縝
&矀�ⅰG�/覜�*忬q5,�1e鈷噓�D��-sc戅翨}e@34朵梯
踙$�&睊g�n﨓�荖
祡5鏍�;<S=驜�>v(鄎\�zg�*g�55頔� f鰴H勾n硬餢h魁觡c�A贞w膐	宯�蝩€�3>臙鷨蚊�IP�6巬峆邽斑A<A虜*冰姆唕L昜形€L䶮临癒數譁7妢餬�~氺L��==z6齭鷔搀妖W莧咏{o^稞u齄伤�;廮L~x瘀嘣��(耺gu^尢窠綝x袶>h溳u�9wmy旟胞|鼾亚肙户Ov'嚳>搦汨溟舴育搘陈丢Ρ毒g鲿�7R{~�
签到失败!原因未知
签到失败!原因未知
【鱼C论坛】：     签到：签到失败!原因未知

任务3执行中

当前书香门第网址为：https://www.txtnovel.pro
请自行核对，如果接下来报错或失败极有可能是网址变了。
请百度一下最新网址，
并手动在环境变量内新建sxmd_host，内容不带https://
示例：www.txtnovel.pro

登陆失败
【书香门第】：登陆失败  
------------任务执行完毕------------

**Comment by Wenmoux** [comment]
12母鸡 书香门第是中文账号密码？
