### ISSUE TITLE
什么值得买签到异常

### ISSUE THREAD

**Issue by jeck5001** [Wenmoux/checkbox#246]
![image](https://user-images.githubusercontent.com/8085554/209456148-aeb77c71-aa15-4410-8174-d980e3b40602.png)
提示：验证码输入错误，请重新输入

**Comment by Cyiming** [comment]
解决了么

**Comment by jeck5001** [comment]
> 解决了么

没有，还是这个提示

**Comment by Mathisdifficult** [comment]
同

**Comment by dh53128** [comment]
同问题。顶一下让佬看到

**Comment by Wenmoux** [comment]
需要验证了 ＼(`Δ’)／快去隔壁用app的吧 奖励还多点
