### ISSUE TITLE
刺猬猫登录状态过期请重新登录

### ISSUE THREAD

**Issue by ttt789-ppo** [Wenmoux/checkbox#248]
刺猬猫的脚本老是提示登录状态过期请重新登录，抓包的cookie只能用一次，第二次运行就过期了，这怎么办？以前还是账号密码登录的时候不会这样

**Comment by Wenmoux** [comment]
@ttt789-ppo 6

**Comment by Wenmoux** [comment]
@ttt789-ppo 没遇到过 你重新登陆了？app里

**Comment by ttt789-ppo** [comment]
> 

有切换账号，因为我有几个账号

**Comment by Wenmoux** [comment]
@ttt789-ppo 都退出了肯定失效阿。
方法1：分身
2：多手机
3：直接清除应用数据切换账号 不要退出
