### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by RouJiANG-14** [Wenmoux/checkbox#25]
function qmsg(msg) {
  return new Promise(async (resolve) => {
    try {        
        if (**sckey**) {
          let url = `https://sctapi.ftqq.com/${sckey}.send`
          let data =`title=${encodeURI("wps记得手动打卡哦")}&desp=${encodeURI(text)}`
          let res = await axios.post(url,data)
          if (res.data.code == 0) {
              console.log("server酱:发送成功");
            } else {
            console.log("server酱:发送失败");
            console.log(res.data.info);
          }
        } else {
          console.log("server酱:你还没有填写**qmsg酱推送key呢**，推送个鸡腿");
        }             
    } catch (err) {
      console.log("Qmsg酱：发送接口调用失败");
      console.log(err);
    }
    resolve();
  });
}
function server(a) {
  return new Promise(async (resolve) => {
    try {
      if (**sckey**) {
        url = `https://sc.ftqq.com/$**{sckey**}.send`;
        res = await $http.post(url, `text=签到盒-每日任务已完成&desp=${a}`);
        if (res.data.errmsg == "success") {
          console.log("server酱:发送成功");
        } else {
          console.log("server酱:发送失败");
        }
      } else {
        console.log("server酱:你还没有填写**qmsg酱推送key**呢，推送个鸡腿");
      }
    } catch (err) {
      console.log("server酱:发送接口调用失败");
      console.log(err);
    }
    resolve();
  });
}
function cp(msg) {
  return new Promise(async (resolve) => {
    try {
      if (**qmsgkey**) {
        let url = `https://push.xuthus.cc/send/${cpkey}?c=${encodeURI(msg)}`;
        let res = await $http.get(url);
        if (res.data.code == 200) {
          console.log("酷推：发送成功");
        } else {
          console.log(res.data);
          console.log("酷推：发送失败!" + res.data.reason);
        }
      } else {
        console.log("酷推：你还没有填写酷推推送key呢，推送个鸡腿");
      }
    } catch (err) {
      console.log("酷推：发送接口调用失败");
      console.log(err);
    }
    resolve();
  });
}
module.exports=sendmsg

在云函数部署的，一直推送不了，看了下代码。
觉得这里是不是弄错了啊？？？ 我不是太懂JS。
我改了酷推的
      if (**cpkey**) {
        let url = `https://push.xuthus.cc/send/${cpkey}?c=${encodeURI(msg)}`;
        let res = await $http.get(url);
        if (res.data.code == 200) {

提示发送成功但是我并没有收到QQ消息，不知道是酷推的问题还是怎么回事，我再试试server酱.

**Comment by Wenmoux** [comment]
复制完忘了改emmmm不过qmsg和server我本地测试没问题(都填了的话)
酷推我没用了不知道
还有server在云函数推送失败正常建议换成turbo版
qmsg你加对好友没

**Comment by Wenmoux** [comment]
因为我一直把三个都填了的
所以就没啥问题 😂

**Comment by RouJiANG-14** [comment]
逐个修改了一下，改成
```
function server(a) {
  return new Promise(async (resolve) => {
    try {
      if (sckey) {
        url = `https://sc.ftqq.com/${sckey}.send`;
        res = await $http.post(url, `text=签到盒-每日任务已完成&desp=${a}`);
        if (res.data.errmsg == "success") {
          console.log("server酱:发送成功");
        } else {
          console.log("server酱:发送失败");
        }
      } else {
        console.log("server酱:你还没有填写server酱推送key呢，推送个鸡腿");
      }
    } catch (err) {
      console.log("server酱:发送接口调用失败");
      console.log(err);
    }
    resolve();
  });
```



server酱的推送正常了，酷推的不知道问题在哪
原来qmsg是另外的推送服务啊，我还以为是新版的server酱，看到下面两个server酱的新旧推送地址，我以为是逐个对应的呢。
