### ISSUE TITLE
申请修复SFACG错误

### ISSUE THREAD

**Issue by PianCat** [Wenmoux/checkbox#256]
任务1执行中
{
  status: { httpCode: 401, errorCode: 502, msgType: 0, msg: '需要登录才能访问该资源' },
  data: null
}
{
  status: { httpCode: 401, errorCode: 502, msgType: 0, msg: '需要登录才能访问该资源' },
  data: null
}
{"entityType":2,"readingDate":"2023-02-15","seconds":9000}
刷阅读时长失败,请重新填写cookie

{
  status: { httpCode: 401, errorCode: 502, msgType: 0, msg: '需要登录才能访问该资源' },
  data: null
}
[]
【SF轻小说】：查询失败⚠️⚠️⚠️需要登录才能访问该资源签到失败[object Object] || 查询失败⚠️⚠️⚠️需要登录才能访问该资源
server酱:发送成功

上面是报错
最新版青龙

**Comment by xingluo233** [comment]
Cookie失效了
