### ISSUE TITLE
脚本需要进行适配

### ISSUE THREAD

**Issue by geelinsir** [Wenmoux/checkbox#262]
- [x] Hires后花园最新域名为dsdlove.com
- [ ] lkong最新接口为https://api.lkong.com/api，post的data为'{"variables":{},"query":"mutation {\n  punch {\n    uid\n    punchday\n    isPunch\n    punchhighestday\n    punchallday\n    __typename\n  }\n}"}'
- [ ] NGA的header需要增加"X-USER-AGENT"字段:"Nga_Official/90601(xxxx)"
- [ ] lenovo脚本已失效，建议改为集成https://github.com/KD-happy/KDCheckin/blob/main/Lenovo.py，从网页侧完成签到
- [ ] meizu接口更换为https://myplus-api.meizu.cn/myplus-muc/u/user/signin，post即可，网页侧cookie每日需要去get https://login.flyme.cn/login/login.html?service=store&appuri=https://myplus-api.meizu.cn/myplus-login/g/login.htm?action=dologin_p&useruri=https://www.meizu.cn/刷新
- [ ] fanruan摇摇乐的reg2更新为“已经摇过”，删掉“奖”，首次执行时收到的网页编码不对会导致结果识别异常
- [ ] duokan可以考虑较少sign1数组数量或者做次数限制，getO函数对应的活动已下线
- [ ] qidian笔芯url改为V2，data增加字段&sessionKey=&banId=0&captchaTicket=&captchaRandStr=&challenge=&validate=&seccode=
- [ ] oshwhub需要用oshwhubReferer、acw_tc、oshwhub_session GET https://oshwhub.com/login?from=https://oshwhub.com/sign_in取cookie再签到
- [ ] 再推荐几个脚本：[KDCheckin的 HLX、PTA、ToolL](https://github.com/KD-happy/KDCheckin)，[dailycheckin的 unicom、heytap、kgqq、cloud189、bilibili](https://sitoi.gitee.io/dailycheckin/)，[NewTab](https://github.com/ZFeng1005/NewTab)/，https://github.com/XcantloadX/AutoCloudSign/blob/master/script/qqmusic.php

**Comment by Wenmoux** [comment]
hires已修改
lenovo nga我多个号测试没问题

别的有空再看

**Comment by geelinsir** [comment]
另外建议可以让各个脚本单独运行（set cookie=xxx），本地运行多个仓库更新cookie得来回跑
