### ISSUE TITLE
QQ阅读的观看视频获取金币

### ISSUE THREAD

**Issue by RouJiANG-14** [Wenmoux/checkbox#29]
不知道这个有没有搞头？谢谢大佬。

**Comment by Wenmoux** [comment]
ziye还是谁来着不是有qq阅读相关脚本的吗

**Comment by RouJiANG-14** [comment]
哦哦哦 我搜索到了。另外大佬WPS的邀请，多用户怎么处理？ 是要把脚本程序复制几份然后分别修改参数么？

**Comment by Wenmoux** [comment]
嗯是 我没改
wps云函数是批量的
这个的话只能这样或者改下脚本
