### ISSUE TITLE
用黄鸟抓起点的cookie和UserId和deviceUid怎么也找不到

### ISSUE THREAD

**Issue by haicao8848** [Wenmoux/checkbox#307]
用黄鸟抓起点的cookie和UserId和deviceUid怎么也找不到
为啥，我吧能看到的都按了都找不到和UserId和deviceUid有关的链接，cookie就更找不到了:(
为啥？？？

**Comment by haicao8848** [comment]
找到了

**Comment by DoiiarX** [comment]
在哪里啊

**Comment by Wenmoux** [comment]
@DoiiarX 把个人中心签到福利都点一遍然后搜索 百分百有。。

**Comment by DoiiarX** [comment]
> @DoiiarX 把个人中心签到福利都点一遍然后搜索 百分百有。。

实在是不行。我弄福利中心会说我环境不安全不显示。然后我直接用APP长按，然后有一个签到按钮，解决了。
