### ISSUE TITLE
希望增加一个 小黑盒 APP 签到和分享任务自动完成

### ISSUE THREAD

**Issue by AkimotoPh** [Wenmoux/checkbox#33]
可以使用 cokkies 登录， 可以获得的 H 币，用于兑换 Steam 游戏

小黑盒 官网 [小黑盒官网](https://xiaoheihe.cn/home)

有类似的仓库，但是年久不维护了： https://github.com/chr233/xhh_auto

**Comment by Wenmoux** [comment]
之前就用的这个
也会封号的
我还在他群里
