### ISSUE TITLE
通知vocechat未配置导致签到日志报错或无法签到

### ISSUE THREAD

**Issue by shusanjing** [Wenmoux/checkbox#334]
当前最新签到脚本+旧版配置文件不含vocechat字段，则无法签到×。
当前最新签到脚本+新配置文件，vocechat字段留空，签到成功但日志报错

字段：
#vocechat
  vocechat: 
    api: 
    uid: 
    key:

日志：
Vocechat: 发送接口调用失败
AxiosError: connect ECONNREFUSED 127.0.0.1:80
    at Function.AxiosError.from (/ql/data/scripts/Wenmoux_checkbox_master/node_modules/axios/dist/node/axios.cjs:841:14)

**Comment by Wenmoux** [comment]
@shusanjing

**Comment by Wenmoux** [comment]
修了 push错脚本了
