### ISSUE TITLE
期望增加库街区内 鸣潮的每日签到

### ISSUE THREAD

**Issue by Crazybbok** [Wenmoux/checkbox#336]
期望增加库街区内 鸣潮的每日签到

**Comment by msyouq** [comment]
前面逛到另一个的写了，https://github.com/sudojia/scripts

**Comment by msyouq** [comment]
> 期望增加库街区内 鸣潮的每日签到

前面逛到另一个的写了，https://github.com/sudojia/scripts

**Comment by Crazybbok** [comment]
> > 期望增加库街区内 鸣潮的每日签到
> 
> 前面逛到另一个的写了，https://github.com/sudojia/scripts

感谢 我看一下
