### ISSUE TITLE
大佬，菠萝包接口校验失败

### ISSUE THREAD

**Issue by zhenghan123** [Wenmoux/checkbox#338]
领取天天分享任务中~
接口校验失败,请确认请求方式

领取每日阅读60分钟任务中~
接口校验失败,请确认请求方式

领取每日阅读120分钟任务中~
接口校验失败,请确认请求方式

领取订阅2章VIP章节任务中~
接口校验失败,请确认请求方式

领取订阅5章VIP章节任务中~
接口校验失败,请确认请求方式

领取打赏任意作品任务中~
接口校验失败,请确认请求方式

领取充值任意金额任务中~
接口校验失败,请确认请求方式

领取订阅1话VIP章节任务中~
接口校验失败,请确认请求方式

**Comment by xingluo233** [comment]
应官方要求，本项目不再提供菠萝包相关脚本
