### ISSUE TITLE
好游快爆云函数运行出错

### ISSUE THREAD

**Issue by way0922** [Wenmoux/checkbox#35]
"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Error: Cannot find module 'cheerio'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:508:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.\u003canonymous\u003e (/var/user/scripts/hykb_gamesign.js:3:14)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)\n    at Module.load (internal/modules/cjs/loader.js:600:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:531:3)","statusCode":430}有时这样，有时直接运行超过900秒

**Comment by Wenmoux** [comment]
阿 游戏签到啊 这个我给忘了 你可以云函数控制台输入 npm install cheerio

**Comment by way0922** [comment]
还是不行，但我在本地运行成功了，谢谢大佬
