### ISSUE TITLE
能否加入王者营地签到即每日任务

### ISSUE THREAD

**Issue by ToSeeAll** [Wenmoux/checkbox#37]
rt

**Comment by Wenmoux** [comment]
github搜一下有王者营地的签到 (我也不玩 角色都没emm

**Comment by ctaoist** [comment]
他那个用不了，脚本里需要用到`WZRY_h5sign`这个环境变量，但并没有给出说明，我自己抓包试了试，提示`H5登录态失效`，但是直接访问referer地址好像又没有失效，大佬要不要来试试 @Wenmoux 可以借号
