### ISSUE TITLE
请问网易云游戏的签到是不是失败了呀

### ISSUE THREAD

**Issue by zhu-ty** [Wenmoux/checkbox#43]
我发现根本签不上了呜呜 这个method被关了吗

Method Not Allowed
The method is not allowed for the requested URL.

**Comment by Wenmoux** [comment]
啊这 我今天是成功了的

**Comment by zhu-ty** [comment]
啊这……不好意思那我继续试试吧
我这边token验证应该是过了
反馈的是在sign那一步失败了……
