### ISSUE TITLE
可以支持下bigfun的登录签到吗

### ISSUE THREAD

**Issue by Yakumo-Yukari** [Wenmoux/checkbox#45]
B站游戏社区 bigfun   登录就算签到成功  所以 每天登录一次就可以了

**Comment by Wenmoux** [comment]
https://github.com/Wenmoux/checkbox/blob/master/scripts/bigfun.js

用网页版的cookie和token 有效期暂未测试

![](https://cdn.jsdelivr.net/gh/Wenmoux/wenpic/other/IMG_20210717_010841.jpg)

**Comment by Wenmoux** [comment]
好像除了签到其他任务经验值没增加
只提现已完成
app里再点一次赞/评论一次 才能领取对应经验值...

**Comment by Yakumo-Yukari** [comment]
> 好像除了签到其他任务经验值没增加
> 只提示已完成
> app里再点一次赞/评论一次 才能领取对应经验值...

网页上登录是直接提示 签到完成 同时增加经验  APP我倒是没试过

**Comment by Wenmoux** [comment]
我是指其它任务...

**Comment by Yakumo-Yukari** [comment]
> 我是指其它任务...

嗯  APP上好像 是这样的  有相应的任务来着

**Comment by Yakumo-Yukari** [comment]
请问  这个可以 用腾讯云函数 部署吗？

**Comment by Wenmoux** [comment]
可以
单独放bugfun到云函数也行
自己弄好依赖
填好cookie以及token
