### ISSUE TITLE
网易云游戏cookie

### ISSUE THREAD

**Issue by gameovertse** [Wenmoux/checkbox#46]
我获取了网易云游戏的cookie，但是填写进去运行就是会出错，请问正确的姿势是怎样的呢？
（在网站，按下F12，然后找到Network，刷新页面，接着在Name里找到index.html，再在Headers里找到cookie。应该是这样的吧？cookie的格式为：timing_user_id=****; _ntes_nnid=****; _ntes_nuid=****）

**Comment by Wenmoux** [comment]
![](https://cdn.jsdelivr.net/gh/Wenmoux/wenpic/other/IMG_20210719_200415.jpg)

请求头里 auth..
网页版
