### ISSUE TITLE
时光相册总是错误

### ISSUE THREAD

**Issue by RouJiANG-14** [Wenmoux/checkbox#48]
手机号格式按照
8612345647478
密码是抓包来的
抓包的内容是：
mobile=2e3d33---03730---1323132---1&password=7f-d667--534-7-6
--是隐藏的
我不知道是不是我抓的不对？？
密码填入后面的7f-d667--534-7-6内容还是提示帐号密码错误。

**Comment by Wenmoux** [comment]
手机号呢
例 8613245784587
前面的86也要

**Comment by RouJiANG-14** [comment]
就是加了86的，依然是提示错误。加了的没加的我都试了。
8613245784587格式的试了，
直接13245784587格式的也试了，都提示帐号密码错误。
86后加mobile的内容的也试了，提示手机号格式不正确。

**Comment by Wenmoux** [comment]
我刚测试两号都没问题..
你抓的网页还是app

**Comment by RouJiANG-14** [comment]
> 我刚测试两号都没问题..
> 你抓的网页还是app

是APP，用VENT抓包的，搞不清楚问题出在哪里，实在没办法，我换了这个大佬的项目：[EverPhotoCheckin](https://github.com/winterssy/EverPhotoCheckin)
谢谢老哥的指点！

**Comment by Wenmoux** [comment]
没试过app
那没事了
