### ISSUE TITLE
好游快爆任务执行异常

### ISSUE THREAD

**Issue by wsdjj** [Wenmoux/checkbox#52]
已经通过了礼仪考试，还是显示先通过考试再运行脚本，是不是我没抓到scookie，直接拿cookie填进去了有感谢😢
![image](https://user-images.githubusercontent.com/76938752/128124103-fc9c28dc-4ecf-4080-8d68-f9b68a3c2af5.jpg)
![Uploading B44436A5-66DC-41A5-ACE8-66BFF316ED96.png…]()

**Comment by Wenmoux** [comment]
更新脚本...
