### ISSUE TITLE
时光相册签到密码总是错误

### ISSUE THREAD

**Issue by wsdjj** [Wenmoux/checkbox#54]
我APP端抓的密码是这个，填上去是错误的

   phone: 86我的手机号

 password: mobile=2e3d333436303d33363d3233333c&password=36333d3333313036

【时光相册每日签到】：登陆失败密码错误

**Comment by Wenmoux** [comment]
道理我都懂
可是你password里为啥还有phone
还有我只试过网页版

**Comment by wsdjj** [comment]
已经可以了，感谢大佬，刚刚突然想到可以在手机上打开时光相册网页版抓登入包的，这样密码就正确了
