### ISSUE TITLE
求多账号怎么部署

### ISSUE THREAD

**Issue by a2518** [Wenmoux/checkbox#56]
求多账号怎么部署

**Comment by Wenmoux** [comment]
@a2518 阿没考虑过多账号

**Comment by ToSeeAll** [comment]
> 求多账号怎么部署

可以试试复制要多账号的js脚本，改个名，再在config里添加对应cookie，最后index添加执行，就可以了，这是目前我能想到的最简单的多账户部署方式

**Comment by Wenmoux** [comment]
✓
