### ISSUE TITLE
龙空签到链接404了

### ISSUE THREAD

**Issue by wsdjj** [Wenmoux/checkbox#60]
hifini和龙空论坛的签到都失败了，龙空是因为签到的链接404，hifini不知道为什么
TypeError: Cannot read property 'cookie' of undefined
    at /var/user/scripts/hifini.js:9:45
    at new Promise (<anonymous>)
    at task (/var/user/scripts/hifini.js:3:12)
    at start (/var/user/index.js:20:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Runtime.exports.main_handler [as handler] (/var/user/index.js:10:3)

**Comment by Wenmoux** [comment]
后者我怀疑你格式错了 比如少了个空格
