### ISSUE TITLE
希望增加得到APP签到

### ISSUE THREAD

**Issue by kerncoola** [Wenmoux/checkbox#7]
![image](https://user-images.githubusercontent.com/13283995/104258523-aa22f500-54ba-11eb-9130-6abaa73f8399.png)

**Comment by SalayDay** [comment]
还有mt论坛签到

**Comment by Wenmoux** [comment]
@SalayDay  mt一直都有啊

**Comment by Wenmoux** [comment]
@kerncoola  得到之前看过然后没写忘了啥问题了 🤐
