### ISSUE TITLE
爱企查领取不完全，什么值得买建议

### ISSUE THREAD

**Issue by 17huiwei** [Wenmoux/checkbox#73]
![aiqicha](https://user-images.githubusercontent.com/5652417/134619419-742220a0-5fd3-4139-8193-d5ae174fb195.png)

另外，我之前用过一个什么值得买的签到，除了签到，还多了自动评论三个贴（据作者说，每日只有前三个有碎银啥的），这是程序地址
https://github.com/xuess/smzdm-sign 我运行没问题，能完成所有任务，但是程序最后无法退出。看老大能不能融合进我们的程序，造福值友。

**Comment by Wenmoux** [comment]
@17huiwei 所以爱企查定时两次阿...这是百度的问题 跑了过一会儿才提示完成

**Comment by Wenmoux** [comment]
@17huiwei 让它后台跑不就好了 定时每天会自动跑的
