### ISSUE TITLE
青龙模式下，如何控制运行时间？

### ISSUE THREAD

**Issue by 17huiwei** [Wenmoux/checkbox#75]
https://githubmemory.com/repo/Wenmoux/checkbox

我在这个里面没有找到添加“定时任务”的内容，是编辑crontab.list这个文件么？

**Comment by Wenmoux** [comment]
？青龙不需要crontab.list
那个是linux下配合crond定时使用的
青龙直接添加任务呀

**Comment by 17huiwei** [comment]
是添加 task index.js还是task node index.js

**Comment by Wenmoux** [comment]
正常情况下是会自动添加的...
ql repo的话
task index.js
ql repo的话就有前缀
