### ISSUE TITLE
求增加网上国网app每日签到

### ISSUE THREAD

**Issue by Mitchell08** [Wenmoux/checkbox#88]
求增加网上国网app每日签到。

![Screenshot_20211014-135921](https://user-images.githubusercontent.com/13077075/137260590-9f7fd855-e7cb-401e-a432-3841be6cfa41.jpg)

**Comment by dh53128** [comment]
同求。顶上去呗

**Comment by wuqiyu007** [comment]
同求。顶上去呗

**Comment by FengNning** [comment]
同求
