### ISSUE TITLE
wps 开团的移植到腾讯云函数的代码

### ISSUE THREAD

**Issue by fhqswcan** [Wenmoux/checkbox#9]
wps 开团的移植到腾讯云函数的代码是不是有问题 测试一下错误

**Comment by Wenmoux** [comment]
[这个](https://github.com/Wenmoux/checkbox/tree/master/scripts/wps/scf) 就是腾讯云云函数的啊 啥问题

**Comment by Wenmoux** [comment]
发下截图

**Comment by fhqswcan** [comment]
部署完成后测试一直是失败状态

**Comment by colorsakura** [comment]
自己更换sid,不要用默认的

**Comment by Wenmoux** [comment]
你倒是说下啥错误😂😂

**Comment by fhqswcan** [comment]
直接提示操作失败

**Comment by fhqswcan** [comment]
未找到函数执行入口文件，请确认代码包入口文件名和 handler 设置是否对应或代码压缩包是否正常。

**Comment by Wenmoux** [comment]
是腾讯云函数吗 还有你用的哪个目录下的代码

**Comment by fhqswcan** [comment]
使用的腾讯云函数

**Comment by fhqswcan** [comment]
使用的是scf 下面的

**Comment by Wenmoux** [comment]
那都没问题啊 你好歹截个图

**Comment by fhqswcan** [comment]
> 那都没问题啊 你好歹截个图

### 
![1](https://user-images.githubusercontent.com/12725476/105606679-c3d70d00-5dd5-11eb-81c1-8661a515ecfd.png)

**Comment by Wenmoux** [comment]
你这是啥 要么手动复制粘贴 要么下载压缩scf的 ...谁知道你具体弄得啥了 ⊙▽⊙

**Comment by fhqswcan** [comment]
> 你这是啥 要么手动复制粘贴 要么下载压缩scf的 ...谁知道你具体弄得啥了 ⊙▽⊙

重新全部部署了 正在测试

**Comment by fhqswcan** [comment]
目前一个问题 更换了SID后 一直提示的是失败 偶尔会出现一次成功

**Comment by fhqswcan** [comment]
![Uploading 1.png…]()

**Comment by fhqswcan** [comment]
非常郁闷

**Comment by fhqswcan** [comment]
![Uploading 1.png…]()

**Comment by Wenmoux** [comment]
图片看不到 (*´﹃｀*)
