### ISSUE TITLE
大佬爱企查脚本部分奖励无法领取

### ISSUE THREAD

**Issue by yueziji** [Wenmoux/checkbox#96]
爱企查能完成任务，但部分奖励没有自动领取，还要手动上一下号，而且还有些任务不会自动完成，比如发表评论啥的，请求大佬更新😂

**Comment by yueziji** [comment]
> @yueziji 跑路了

那好吧😂

**Comment by Wenmoux** [comment]
@yueziji 所以我定时两次是为了啥....爱企查还有发表评论的吗？

**Comment by yueziji** [comment]
> @yueziji 所以我定时两次是为了啥....爱企查还有发表评论的吗？

还有个发表与回复观点，我也是每天两次，但还是有漏领的😂
